[package]
name = "fo_bindgen_generate"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = { version = "0.59" }
serde = { version = "1", features = ["derive"]}
toml = "0.5"

[workspace]
